### ISSUE TITLE
Some questions regarding conclusion

### ISSUE THREAD

**Issue by pocketbroadcast** [madflojo/blog#48]
Hi Benjamin!,

First of all, nice article!

Btw., I found the conclusion a little bit missleading and wanted to note and ask a few things for clarification:
You wrote earlier in the article: 

> The difference is simple, the `/etc/profile` is executed only for interactive shells and the `/etc/bashrc` is executed for both interactive and non-interactive shells.

Thus, interactive shells use `/etc/profile` and `/etc/bashrc` while non-interactive shells only use `/etc/bashrc`.

Later on in the conclusion you state: 

> In my case the applications child processes are not recognizing the umask value set in /etc/profile but do recognize the value in /etc/bashrc. This tells me that the subprocess is starting as a non-interactive shell.

The umask of `/etc/bashrc` simply overrides the umask from `/etc/profile` as if you call umask twice on the command line.

> While the suggested route of modifying environmental variables is to add a shell script into `/etc/profile.d` in my case it is better to set the umask value in the `/etc/bashrc`.

Why is it better to set environmental variables in `/etc/profile.d`?
Wouldn't this conclude in not having all environment variables set for non-interactive shells?

Sry for the long post.

Kind regards, 
pocketbroadcast

**Comment by madflojo** [comment]
Howdie @pocketbroadcast,

Sorry for the late reply as I just saw this.

So I'd have to go back and lookup some of the same research I did originally but I think what I was trying to state is that if I only put my setting in `/etc/profile` my subprocesses did not pickup the umask setting. But when I put it in the `/etc/bashrc` file it did.

From what I remember the `/etc/bashrc` is executed for all types of logins, where `/etc/profile` is executed only for interactive shells. So the use case I was working with wasn't executing `/etc/profile`, only `/etc/bashrc`.

At least, thats what I remember off the top of my head.

Regards to the `/etc/profile.d` question. What I mean is, the convention is to place login scripts that modify environmental variables within `/etc/profile.d`. What I was trying to show with the article is that, while that might be conventional wisdom, it did not fit the specific case I was running into.
