### ISSUE TITLE
Real example of logging implementation in Golang package.

### ISSUE THREAD

**Issue by lesovsky** [madflojo/blog#54]
Hi Benjamin,

I've read your your recent post/slides "How I Structure Go Packages" and I'd like asking about logging implementation. 
I faced with necessity of logging implementation in my tiny [app/package](https://github.com/lesovsky/noisia) but due to lack of skills don't know how to do that in a right way.

Could you provide some real world examples (from Golang standard library or something else) where logging is implemented in a way mentioned in the post.

I also create a SO [question](https://stackoverflow.com/questions/62807327/proper-logging-implementation-in-golang-package), where I asked the same question.

I'd be very appreciated if you could point me to a right example.

P.S. I'm sorry that I created an issue which is not directly related to this repo, but I have not found any other your contacts ))) I'm not Twitter/Linkedin user.

**Comment by madflojo** [comment]
Howdie @lesovsky, I don't usually see issues here so this one slipped by me. 

As far as examples go you can look at:

- https://github.com/madflojo/go-quick
- https://github.com/madflojo/hord

Go Quick is an example app that structures logging as I described in my post and Hord is a database library that returns errors to users as they call it. If you structure your application and packages right it should be a pretty rare occasion that simply returning the error is not good enough. 

But for those rare occasions, you can create a logger struct like described in your SO answers. Or use an ErrFunc as I do in madflojo/tasks. https://github.com/madflojo/tasks/blob/master/tasks.go#L126-L128

**Comment by lesovsky** [comment]
Thank you for examples. I added a logger interface, hence end-user can use its own implementation or use default logger from package.
